product=input("Product bought:")
quantity=input("Hou much do you need?")
price=input("Enter cost:")
bill=int(quantity)*float(price)
print()
print()
print("___________")
print("Your Invoice")
print("1. Product:",product)
print("2. Quantity:",quantity)
print("3. Price:",price)
print("Your bill is:",bill)
print()
print()